-- Add legal content columns to site_settings for dynamic Privacy Policy and Terms of Service
-- Run this in Supabase SQL Editor if your existing table does not have these fields yet.

alter table public.site_settings
  add column if not exists privacy_policy text,
  add column if not exists terms_of_service text;

update public.site_settings
set
  privacy_policy = coalesce(
    nullif(trim(privacy_policy), ''),
    'Last Updated: June 20, 2026\n\nWelcome to Giver Recording Studio. We value your privacy and are committed to protecting your personal information.\n\n1. Data Collection\nWe may collect your name, email address, phone number, booking details, and messages you submit through forms on this website.\n\n2. Cookies\nThis website may use cookies and similar technologies to improve user experience, remember preferences, and analyze site traffic.\n\n3. Contact Forms and Bookings\nWhen you submit contact forms or booking requests, the information is stored securely to help us respond to your request and manage studio services.\n\n4. Email Addresses\nEmail addresses you provide are used only for communication related to inquiries, bookings, submissions, and service updates.\n\n5. Music Submissions\nFiles, metadata, and details submitted through our artist submission tools are processed for review and service delivery.\n\n6. User Responsibilities\nYou are responsible for ensuring that all information and files you submit are accurate, lawful, and do not infringe third-party rights.\n\n7. Copyright and Ownership\nAll website content, branding, and media remain the property of Giver Recording Studio or respective owners unless stated otherwise.\n\n8. Limitation of Liability\nWhile we strive to maintain secure and reliable services, Giver Recording Studio is not liable for indirect or consequential damages resulting from use of this website.\n\n9. Contact Information\nIf you have privacy-related questions, contact us at giverrecords@gmail.com.\n\nBy continuing to use this website, you agree to this Privacy Policy.'
  ),
  terms_of_service = coalesce(
    nullif(trim(terms_of_service), ''),
    'Last Updated: June 20, 2026\n\nWelcome to Giver Recording Studio. By using this website, you agree to the following terms and conditions.\n\nAcceptance of Terms\n\nBy accessing or using our website and services, you agree to comply with these Terms of Service.\n\nServices\n\nGiver Recording Studio provides music production, recording, mixing, mastering, beat licensing, and related creative services.\n\nIntellectual Property\n\nAll music, beats, artwork, logos, and content displayed on this website are the property of Giver Recording Studio or their respective owners. Unauthorized copying, redistribution, or commercial use is prohibited without written permission.\n\nUser Submissions\n\nUsers who submit music, messages, or booking requests are responsible for the content they provide. Illegal, offensive, or copyrighted material belonging to others must not be submitted.\n\nPayments and Bookings\n\nPayments made for studio sessions and services are subject to the agreed terms between the client and Giver Recording Studio. Booking dates may be adjusted due to unforeseen circumstances.\n\nExternal Links\n\nOur website may contain links to third-party platforms such as YouTube, Instagram, TikTok, WhatsApp, and X (Twitter). We are not responsible for the content or policies of these external websites.\n\nLimitation of Liability\n\nGiver Recording Studio shall not be held liable for any direct or indirect damages arising from the use of this website or its services.\n\nChanges to These Terms\n\nWe reserve the right to update these Terms of Service at any time. Changes become effective immediately after publication on this website.\n\nContact Information\n\nFor questions regarding these Terms of Service, please contact:\n\nGiver Recording Studio\n\nEmail: giverrecords@gmail.com\n\nLagos, Nigeria\n\nThank you for choosing Giver Recording Studio.'
  )
where id = 1;
